stages:
  - zip_repo 
  - upload_to_s3

zip_repo:
  stage: zip_repo
  #image:
  #  name: ubuntu
  script: 
    - gzip -c * > drem.zip
  artifacts:
    paths:
    - drem.zip

upload_to_s3:
  stage: upload_to_s3
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - ls -lah