stages:
  - zip_repo 
  - upload_to_s3

zip_repo:
  stage: zip_repo
  script: 
    - ls -lah
    - gzip -c . > drem.zip

upload_to_s3:
  stage: upload_to_s3
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - ls -lah