repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-ast
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or: [javascript, css]
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "git diff --diff-filter=d --cached --name-only | grep -E '\.(js|jsx)$' | xargs -I % sh -c 'git show ":%" | ./website/node_modules/.bin/eslint --stdin --stdin-filename "%";'"
        language: node
      - id: lower-case-file-names-only
        name: lower case file names only
        entry: filenames must be lower-case
        language: fail
        files: '[^a-z0-9./-]'
        types_or: [javascript, jsx, ts, tsx, python]
